import type { WorldBuilderProject } from '../generated/project'

// Starter document for a new session: the Phase 0 test-city vocabulary and
// globals (schema/fixtures/valid/test-city.json) with empty geometry, so the
// fixture city is authorable from a blank canvas. This is what a session
// starts from before features/project/persistence's load-on-mount resolves
// (or when there's nothing to load yet); #19 still owns the full
// list/open/rename/autosave project-management UI.
export function createDefaultProject(): WorldBuilderProject {
  return {
    schemaVersion: 2,
    meta: { name: 'Untitled city' },
    global: {
      artStylePrompt:
        'top-down hand-drawn fantasy city map, ink linework with muted watercolour wash, parchment tone',
      palette: ['#c9b48a', '#7a6a4f', '#5a8f3c', '#3c6e8f', '#8f3c3c'],
      eraNotes: 'late-medieval trading city, northern European character',
      canvas: { width: 2048, height: 1536 },
      output: { width: 12288, height: 9216 },
      scale: { metersPerUnit: 1.5 },
      defaultFillType: 'farmland',
      seed: 20260707,
    },
    vocabulary: [
      {
        id: 'farmland',
        category: 'region',
        displayName: 'Farmland',
        maskColor: '#b8a860',
        promptFragment: 'patchwork farmland, hedgerows, scattered farmhouses',
        streetDensity: 0.05,
      },
      {
        id: 'water',
        category: 'region',
        displayName: 'Water',
        maskColor: '#3c6e8f',
        promptFragment: 'deep river water, subtle current lines',
        streetDensity: 0,
      },
      {
        id: 'forest',
        category: 'region',
        displayName: 'Forest',
        maskColor: '#2e5c2e',
        promptFragment: 'dense broadleaf forest canopy',
        streetDensity: 0,
      },
      {
        id: 'marsh',
        category: 'region',
        displayName: 'Marsh',
        maskColor: '#6e8f5c',
        promptFragment: 'reedy marshland, standing water, boardwalks',
        streetDensity: 0.02,
      },
      {
        id: 'castle-ward',
        category: 'region',
        displayName: 'Castle ward',
        maskColor: '#8f3c3c',
        promptFragment: 'castle keep, curtain walls, baileys, banners',
        streetDensity: 0.2,
      },
      {
        id: 'noble-quarter',
        category: 'region',
        displayName: 'Noble quarter',
        maskColor: '#c05c8f',
        promptFragment: 'grand manors, private gardens, wide avenues',
        streetDensity: 0.35,
      },
      {
        id: 'temple-district',
        category: 'region',
        displayName: 'Temple district',
        maskColor: '#e0d0a0',
        promptFragment: 'temples and shrines, cloisters, processional square',
        streetDensity: 0.4,
      },
      {
        id: 'market-district',
        category: 'region',
        displayName: 'Market district',
        maskColor: '#e08f3c',
        promptFragment: 'market squares, stalls, guildhalls, dense shopfronts',
        streetDensity: 0.75,
      },
      {
        id: 'artisan-district',
        category: 'region',
        displayName: 'Artisan district',
        maskColor: '#a0703c',
        promptFragment: 'workshops, kilns, courtyard smithies',
        streetDensity: 0.65,
      },
      {
        id: 'residential-dense',
        category: 'region',
        displayName: 'Dense residential',
        maskColor: '#c0a070',
        promptFragment: 'tightly packed timber-frame houses, narrow lanes',
        streetDensity: 0.85,
      },
      {
        id: 'residential-modest',
        category: 'region',
        displayName: 'Modest residential',
        maskColor: '#d0b890',
        promptFragment: 'modest row houses, small yards',
        streetDensity: 0.6,
      },
      {
        id: 'slum',
        category: 'region',
        displayName: 'Slum',
        maskColor: '#705848',
        promptFragment: 'ramshackle lean-tos, crooked alleys, patched roofs',
        streetDensity: 1,
      },
      {
        id: 'docks',
        category: 'region',
        displayName: 'Docks',
        maskColor: '#4c5c70',
        promptFragment: 'wharves, cranes, moored ships, warehouses',
        streetDensity: 0.55,
      },
      {
        id: 'warehouse-district',
        category: 'region',
        displayName: 'Warehouse district',
        maskColor: '#707070',
        promptFragment: 'long warehouse rows, wagon yards',
        streetDensity: 0.45,
      },
      {
        id: 'garrison',
        category: 'region',
        displayName: 'Garrison',
        maskColor: '#903030',
        promptFragment: 'barracks, drill yard, armoury',
        streetDensity: 0.25,
      },
      {
        id: 'graveyard',
        category: 'region',
        displayName: 'Graveyard',
        maskColor: '#8f8f9f',
        promptFragment: 'walled graveyard, mausoleums, cypress trees',
        streetDensity: 0.05,
      },
      {
        id: 'park',
        category: 'region',
        displayName: 'Park',
        maskColor: '#5a8f3c',
        promptFragment: 'public green, tree-lined paths',
        streetDensity: 0.1,
      },
      {
        id: 'ruins',
        category: 'region',
        displayName: 'Ruins',
        maskColor: '#5c5040',
        promptFragment: 'burned-out ruins, collapsed roofs, rubble',
        streetDensity: 0.3,
      },
      {
        id: 'landmark',
        category: 'point',
        displayName: 'Landmark',
        promptFragment: 'a distinctive landmark building',
      },
      {
        id: 'gate',
        category: 'point',
        displayName: 'City gate',
        promptFragment: 'fortified gatehouse with towers',
      },
    ],
    labelStyles: [],
    regions: [],
    lines: [],
    points: [],
    labels: [],
  }
}
